module.exports = [
  ["blazuliteTutorial.ogg",        "1. Tutorial by Blazulite.ogg"],
  ["waterflameSwirl.ogg",          "2. Swirl by Waterflame.ogg"],
  ["apoplexyBeeHunter.ogg",        "3. Apoplexy by Bee Hunter.ogg"],
  ["dimrain47Infernoplex.ogg",     "4. Infernoplex by Dimrain47.ogg"],
  ["dimrain47ForsakenNeon.ogg",    "5. Forsaken Neon by Dimrain47.ogg"],
  ["waterflameOctagonForce.ogg",   "6. Octagon Force by Waterflame.ogg"],
  ["waterflameSkyManeuvers.ogg",   "7. Sky Maneuvers by Waterflame.ogg"],
  ["waterflameHyperspin.ogg",      "8. Hyperspin by Waterflame.ogg"],
  ["nonominoFunnyCat.ogg",         "9. Funny Cat by nonomino.ogg"],
  ["tmm43UltimateDestruction.ogg", "10. Ultimate Destruction by TMM43.ogg"],
  ["madhousedudeFlock.ogg",        "11. Flock by madhousedude.ogg"],
  ["goukisanBetrayalOfFear.ogg",   "12. Betrayal Of Fear by Goukisan.ogg"],
  ["tmm43the7thday.ogg",           "13. The 7th Day by TMM43.ogg"],
  ["djNateThermodynamix.ogg",      "14. Thermodynamix by dj-Nate.ogg"],
  ["jewelz123SilentHill.ogg",      "15. Silent Hill (Dubstep) by Aydin-Jewelz123.ogg"],
  ["kid2willFireAura.ogg",         "16. Fire Aura by Kid2Will.ogg"],
  ["awakeSupernova.ogg",           "17. Awake - Supernova by Rawrthaas.ogg"],
  ["dimrain47EveryEnd.ogg",        "18. Every End by Dimrain47.ogg"],
  ["waterflameHauntedWoods.ogg",   "19. Haunted Woods by Waterflame.ogg"],
  ["dimrain47TwilightTechno.ogg",  "20. Twilight Techno by Dimrain47.ogg"],
  ["waterflameCrowdControl.ogg",   "21. Crowd Control by Waterflame.ogg"],
  ["kevinmacleodBlipStream.ogg",   "22. Blip Stream by Kevin Macleod.ogg"],
  ["aryxilCityOutLoud.ogg",        "23. City Out Loud by Aryxil.ogg"],
  ["blazuliteMenuTheme.ogg",       "X. Menu Theme by Blazulite.ogg"],
  ["andrewCrTimeAttack.ogg",       "X. Time Attack by AndrewCR.ogg"],
];
